### ISSUE TITLE
centos 7 microk8s.join as a worker

### ISSUE THREAD

**Issue by VenkySVR** [canonical/microk8s#3857] opened 2023-03-19 10:41 UTC
Traceback (most recent call last):
  File "/snap/microk8s/4595/scripts/wrappers/join.py", line 981, in <module>
    join(prog_name="microk8s join")
  File "/snap/microk8s/4595/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/4595/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/4595/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/4595/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/4595/scripts/wrappers/join.py", line 974, in join
    join_dqlite(connection_parts, verify, worker)
  File "/snap/microk8s/4595/scripts/wrappers/join.py", line 766, in join_dqlite
    join_dqlite_worker_node(info, master_ip, master_port, token)
  File "/snap/microk8s/4595/scripts/wrappers/join.py", line 834, in join_dqlite_worker_node
    update_cert_auth_kubeproxy(token, info["ca"], master_ip, master_port, hostname_override)
  File "/snap/microk8s/4595/scripts/wrappers/join.py", line 427, in update_cert_auth_kubeproxy
    cert = get_client_cert(master_ip, master_port, "kube-proxy", proxy_token, "system:kube-proxy")
  File "/snap/microk8s/4595/scripts/wrappers/join.py", line 281, in get_client_cert
    subprocess.check_call(cmd_cert.split(), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/snap/microk8s/4595/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/snap/microk8s/4595/usr/bin/openssl', 'req', '-new', '-sha256', '-key', '/var/snap/microk8s/current/certs/kube-proxy.key', '-out', '/var/snap/microk8s/current/certs/kube-proxy.csr', '-subj', '/CN=system:kube-proxy']' returned non-zero exit status 1.

**Comment by sachinkumarsingh092** [comment] 2023-03-20 08:21
Hi @VenkySVR, can you please give a brief description of what you are trying to do along with minimal steps to reproduce it? Also, can you do a `microk8s inspect` and provide the tarball so we can look further into this?

**Comment by VenkySVR** [comment] 2023-03-20 09:18
I am trying create multi-cluster using microk8s, where my control plane is running in Ubuntu and I want to join slave node which has Centos.

In my slave node(centos):

[centos@slave-centos ~]$ microk8s join 192.168.55.102:25000/ad67de6f54f916202e66237b1ec61f9b/90e27ec97245 --worker

Contacting cluster at 192.168.55.102
Traceback (most recent call last):
  File "/snap/microk8s/4595/scripts/wrappers/join.py", line 981, in <module>
    join(prog_name="microk8s join")
  File "/snap/microk8s/4595/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/4595/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/4595/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/4595/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/4595/scripts/wrappers/join.py", line 974, in join
    join_dqlite(connection_parts, verify, worker)
  File "/snap/microk8s/4595/scripts/wrappers/join.py", line 766, in join_dqlite
    join_dqlite_worker_node(info, master_ip, master_port, token)
  File "/snap/microk8s/4595/scripts/wrappers/join.py", line 834, in join_dqlite_worker_node
    update_cert_auth_kubeproxy(token, info["ca"], master_ip, master_port, hostname_override)
  File "/snap/microk8s/4595/scripts/wrappers/join.py", line 427, in update_cert_auth_kubeproxy
    cert = get_client_cert(master_ip, master_port, "kube-proxy", proxy_token, "system:kube-proxy")
  File "/snap/microk8s/4595/scripts/wrappers/join.py", line 281, in get_client_cert
    subprocess.check_call(cmd_cert.split(), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/snap/microk8s/4595/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/snap/microk8s/4595/usr/bin/openssl', 'req', '-new', '-sha256', '-key', '/var/snap/microk8s/current/certs/kube-proxy.key', '-out', '/var/snap/microk8s/current/certs/kube-proxy.csr', '-subj', '/CN=system:kube-proxy']' returned non-zero exit status 1.


The microk8s inspect gives this log.

[centos@slave-centos ~]$ microk8s inspect
Inspecting system
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-kubelite is running
  Service snap.microk8s.daemon-k8s-dqlite is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy openSSL information to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting dqlite
  Inspect dqlite

Building the report tarball
  Report tarball is at /var/snap/microk8s/4595/inspection-report-20230320_144342.tar.gz

**Comment by neoaggelos** [comment] 2023-03-20 12:12
Hi @VenkySVR. This sounds similar to an issue with the openssl command that was fixed sometime back https://github.com/canonical/microk8s/issues/3715. The PR with the fix is in https://github.com/canonical/microk8s/pull/3717, and has been backported to the 1.25 and 1.26 branches.

Due to a breaking issue we found and have since fixed, this bugfix has not yet found its way to the stable 1.25 and 1.26 branches. Can you try installing microk8s from the respective edge channel:

```
# if already installed (use 1.25/edge if on 1.25)
sudo snap refresh microk8s --channel 1.26/edge

# if not installed
sudo snap install microk8s --channel 1.26/edge --classic
```

And see if the error persists? Thanks a lot!

**Closed** 2023-03-20 14:07 UTC
Labels: kind/bug
