### ISSUE TITLE
Fresh install of microK8s won't come up

### ISSUE THREAD

**Issue by AuqW9cQ** [canonical/microk8s#4451] opened 2024-03-05 13:01 UTC
#### Summary
on a freshly installed Debian bookworm microK8s just won't come up

#### What Should Happen Instead?
Start normally and get ready

#### Reproduction Steps
1. `sudo snap install microk8s --classic --channel:1.29/stable`
2. Wait....
3. Wait....
4. Wait...

 5. 
```
microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
```

 6.
 ```
microk8s kubectl get nodes
NAME                 STATUS     ROLES    AGE   VERSION
cluster-wf-essen01   NotReady   <none>   78m   v1.29.2
microk8s kubectl get all --all-namespaces
NAMESPACE     NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes   ClusterIP   10.152.183.1    <none>        443/TCP                  79m
kube-system   service/kube-dns     ClusterIP   10.152.183.10   <none>        53/UDP,53/TCP,9153/TCP   79m

NAMESPACE     NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/calico-node   0         0         0       0            0           kubernetes.io/os=linux   78m

NAMESPACE     NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns                   0/1     0            0           79m
kube-system   deployment.apps/calico-kube-controllers   0/1     0            0           78m
```

#### Introspection Report
[inspection-report-20240305_125246.tar.gz](https://github.com/canonical/microk8s/files/14495068/inspection-report-20240305_125246.tar.gz)

```
inxi
CPU: quad core Intel Core i5-6500T (-MCP-) speed/min/max: 2700/800/3100 MHz
Kernel: 6.1.0-18-amd64 x86_64 Up: 49m Mem: 917.4/7821.8 MiB (11.7%)
Storage: 119.24 GiB (2.4% used) Procs: 131 Shell: Bash inxi: 3.3.26

```

#### Can you suggest a fix?
No

**Comment by neoaggelos** [comment] 2024-03-05 13:03
Possibly a duplicate of https://github.com/canonical/microk8s/issues/4361?

**Comment by neoaggelos** [comment] 2024-03-05 13:05
See https://github.com/canonical/microk8s/issues/4361#issuecomment-1916968353 for a possible solution

**Comment by AuqW9cQ** [comment] 2024-03-05 14:18
Thanks for your response seems to be the same problem.

Cause I could not find an official stable 6.5 kernel for Debian 12 I am now at 1.28.

```
microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # (core) CoreDNS
    ha-cluster           # (core) Configure high availability on the current node
    helm                 # (core) Helm - the package manager for Kubernetes
    helm3                # (core) Helm 3 - the package manager for Kubernetes
  disabled:
    cert-manager         # (core) Cloud native certificate management
    cis-hardening        # (core) Apply CIS K8s hardening
    community            # (core) The community addons repository
    dashboard            # (core) The Kubernetes dashboard
    gpu                  # (core) Automatic enablement of Nvidia CUDA
    host-access          # (core) Allow Pods connecting to Host services smoothly
    hostpath-storage     # (core) Storage class; allocates storage from host directory
    ingress              # (core) Ingress controller for external access
    kube-ovn             # (core) An advanced network fabric for Kubernetes
    mayastor             # (core) OpenEBS MayaStor
    metallb              # (core) Loadbalancer for your Kubernetes cluster
    metrics-server       # (core) K8s Metrics Server for API access to service metrics
    minio                # (core) MinIO object storage
    observability        # (core) A lightweight observability stack for logs, traces and metrics
    prometheus           # (core) Prometheus operator for monitoring and logging
    rbac                 # (core) Role-Based Access Control for authorisation
    registry             # (core) Private image registry exposed on localhost:32000
    rook-ceph            # (core) Distributed Ceph storage using Rook
    storage              # (core) Alias to hostpath-storage add-on, deprecated

```

**Closed** 2024-03-05 14:31 UTC
