### ISSUE TITLE
x509: certificate is not valid for any names

### ISSUE THREAD

**Issue by jepson66** [canonical/microk8s#4091] opened 2023-07-18 08:46 UTC
When I want to enter the pod, I execute kubectl exec -it xxxx -- sh, prompting x509: certificate is not valid for any names, but wanted to match kubernetes-master01

![image](https://github.com/canonical/microk8s/assets/108441697/bc2e1231-ec7e-430f-bf27-92ec9e29b0a8)

Microk8s inspect is normal
![image](https://github.com/canonical/microk8s/assets/108441697/31302dff-7ee6-4970-8948-dca98748fe7a)

**Comment by jepson66** [comment] 2023-07-18 11:25
@ktsakalozos,I'm using latest/edge/ha-preview, v1.27.3

**Comment by ktsakalozos** [comment] 2023-07-19 08:19
Thank you for trying the latest track and giving us feedback, be aware however this track may be unstable. The issue you are reporting I believe is addressed in the referenced PR, could you give it a try? You will need to setup a fresh cluster.

I am also interested in the `ha-preview`, how did you end up using this channel? It has been years since the HA work is merged into the main branch.

**Comment by neoaggelos** [comment] 2023-07-21 19:56
This should be now fixed with #4099, @jepson66 it would be appreciated if you can try again with the latest build and verify. Thanks a lot!

**Comment by ktsakalozos** [comment] 2023-07-24 08:25
Thank you for reporting this @jepson66. The issue seems to be addressed. Please feel free to re-open the issue is you are able to reproduce it again.

**Closed by ktsakalozos** 2023-07-24 08:25 UTC
