### ISSUE TITLE
Cluster fails enabling observability add-on 

### ISSUE THREAD

**Issue by jpnorenam** [canonical/microk8s#3472] opened 2022-09-28 12:47 UTC
#### Summary
Trying to enable the `observability` add-on in a microk8s cluster v1.25.0 results in the following error:

```
Error: UPGRADE FAILED: failed to create resource: Endpoints "kube-prom-stack-kube-prome-kube-controller-manager" is invalid: [subsets[0].addresses[0].ip: Invalid value: "172.27.56.22,172.27.56.25,172.27.56.24": must be a valid IP address, (e.g. 10.9.8.7 or 2001:db8::ffff), subsets[0].addresses[0].ip: Invalid value: "172.27.56.22,172.27.56.25,172.27.56.24": must be a valid IP address]
```

#### Reproduction Steps
1. Created a microk8s cluster over lxd
```
~$ lxc list
+-----------------+---------+-----------------------------+------+-----------+-----------+------------+
|      NAME       |  STATE  |            IPV4             | IPV6 |   TYPE    | SNAPSHOTS |  LOCATION  |
+-----------------+---------+-----------------------------+------+-----------+-----------+------------+
| microk8s-node00 | RUNNING | 172.27.56.24 (eth0)         |      | CONTAINER | 0         | node01ob56 |
|                 |         | 10.1.223.128 (vxlan.calico) |      |           |           |            |
+-----------------+---------+-----------------------------+------+-----------+-----------+------------+
| microk8s-node01 | RUNNING | 172.27.56.25 (eth0)         |      | CONTAINER | 0         | node02ob56 |
|                 |         | 10.1.47.64 (vxlan.calico)   |      |           |           |            |
+-----------------+---------+-----------------------------+------+-----------+-----------+------------+
| microk8s-node02 | RUNNING | 172.27.56.22 (eth0)         |      | CONTAINER | 0         | node04ob56 |
|                 |         | 10.1.44.192 (vxlan.calico)  |      |           |           |            |
+-----------------+---------+-----------------------------+------+-----------+-----------+------------+

~$ mkctl get nodes
NAME              STATUS   ROLES    AGE   VERSION
microk8s-node02   Ready    <none>   15h   v1.25.0
microk8s-node01   Ready    <none>   15h   v1.25.0
microk8s-node00   Ready    <none>   15h   v1.25.0
```
2. Enabled the `observability` add-on in the created cluster
```
~$ mk enable observability
Infer repository core for addon observability
Addon core/dns is already enabled
Addon core/helm3 is already enabled
Addon core/hostpath-storage is already enabled
Enabling observability
"prometheus-community" already exists with the same configuration, skipping
"grafana" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "grafana" chart repository
...Successfully got an update from the "prometheus-community" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: UPGRADE FAILED: failed to create resource: Endpoints "kube-prom-stack-kube-prome-kube-controller-manager" is invalid: [subsets[0].addresses[0].ip: Invalid value: "172.27.56.22,172.27.56.25,172.27.56.24": must be a valid IP address, (e.g. 10.9.8.7 or 2001:db8::ffff), subsets[0].addresses[0].ip: Invalid value: "172.27.56.22,172.27.56.25,172.27.56.24": must be a valid IP address]
```

**Comment by neoaggelos** [comment] 2022-09-28 16:45
Duplicate of https://github.com/canonical/microk8s-core-addons/issues/104

**Closed by neoaggelos** 2022-09-28 16:45 UTC
