### ISSUE TITLE
Cluster DNS failure between nodes microk8s 1.26.0

### ISSUE THREAD

**Issue by ctromans** [canonical/microk8s#3666] opened 2023-01-13 12:20 UTC
#### Summary

Three node bare metal cluster, microk8s 1.26.0 on Ubuntu 22.04.  Two worker nodes, one master.  Installed mayastor using:

microk8s enable mayastor

A number of the constituent pods get stuck in Init:0/x, awaiting successful probes of other services within mayastor, which are running but they can't get a response through the network.  For example:

microk8s.kubectl get pods -n mayastor -o wide
NAME                                     READY   STATUS     RESTARTS        AGE   IP              NODE             NOMINATED NODE   READINESS GATES
mayastor-fztq2                           0/1     Init:0/3   0               23m   192.168.69.10   node-1   <none>           <none>
csi-controller-54ccfcfbcc-vxrbx          0/3     Init:0/1   0               23m   192.168.69.12   node-3   <none>           <none>
mayastor-csi-rhd78                       2/2     Running    0               23m   192.168.69.10   node-1   <none>           <none>
mayastor-csi-wqq2j                       2/2     Running    0               23m   192.168.69.11   node-2   <none>           <none>
etcd-ck6p44g5tm                          1/1     Running    0               22m   10.1.75.221     node-2   <none>           <none>
core-agents-55d76bb877-2jtvn             1/1     Running    0               23m   10.1.202.25     node-1   <none>           <none>
msp-operator-74ff9cf5d5-gdmz6            1/1     Running    0               23m   10.1.202.22     node-1   <none>           <none>
rest-77d69fb479-grnqh                    1/1     Running    0               23m   10.1.75.220     node-2   <none>           <none>
mayastor-f22ms                           1/1     Running    0               23m   192.168.69.11   node-2   <none>           <none>
mayastor-csi-8wc5b                       2/2     Running    0               23m   192.168.69.12   node-3   <none>           <none>
mayastor-5xlw8                           0/1     Init:1/3   0               23m   192.168.69.12   node-3   <none>           <none>
etcd-operator-mayastor-65f9967f5-f96j5   1/1     Running    6 (7m21s ago)   23m   10.1.202.23     node-1   <none>           <none>

microk8s.kubectl get services -A -o wide
NAMESPACE        NAME              TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                  AGE   SELECTOR
default          kubernetes        ClusterIP      10.152.183.1     <none>           443/TCP                  13h   <none>
kube-system      kube-dns          ClusterIP      10.152.183.10    <none>           53/UDP,53/TCP,9153/TCP   13h   k8s-app=kube-dns
metallb-system   webhook-service   ClusterIP      10.152.183.75    <none>           443/TCP                  13h   component=controller
minio-operator   operator          ClusterIP      10.152.183.76    <none>           4222/TCP,4221/TCP        13h   name=minio-operator,operator=leader
minio-operator   console           ClusterIP      10.152.183.194   <none>           9090/TCP,9443/TCP        13h   app=console
jupyter          hub               ClusterIP      10.152.183.174   <none>           8081/TCP                 13h   app=jupyterhub,component=hub,release=jupyterhub
jupyter          proxy-api         ClusterIP      10.152.183.239   <none>           8001/TCP                 13h   app=jupyterhub,component=proxy,release=jupyterhub
jupyter          proxy-public      LoadBalancer   10.152.183.190   192.168.69.100   443:32672/TCP            13h   component=proxy,release=jupyterhub
mayastor         core              ClusterIP      None             <none>           50051/TCP                17m   app=core-agents
mayastor         rest              ClusterIP      10.152.183.30    <none>           8080/TCP,8081/TCP        17m   app=rest
mayastor         etcd-client       ClusterIP      10.152.183.120   <none>           2379/TCP                 16m   app=etcd,etcd_cluster=etcd
mayastor         etcd              ClusterIP      None             <none>           2379/TCP,2380/TCP        16m   app=etcd,etcd_cluster=etcd

Note the three mayastor pod replicas, where only node-2 (the master) has started successfully.  Checking logs:

microk8s.kubectl logs mayastor-f22ms registration-probe -n mayastor
nc: bad address 'core'
Waiting for registration service...
nc: bad address 'core'
Waiting for registration service...
_(many repeats)_
nc: bad address 'core'
Waiting for registration service...
core (10.1.202.25:50051) open

The ones that haven't started successfully:

microk8s.kubectl logs mayastor-fztq2 registration-probe -n mayastor
nc: bad address 'core'
Waiting for registration service...
nc: bad address 'core'
Waiting for registration service...
nc: bad address 'core'
_(forever)_

microk8s.kubectl exec -i -t mayastor-fztq2 --container registration-probe -n mayastor -- /bin/sh
/ # nslookup core
Server:    10.152.183.10
Address 1: 10.152.183.10
_(long wait)_
nslookup: can't resolve 'core'

#### What Should Happen Instead?

I would expect the address to resolve immediately and return enabling the mayastor pods to start.

**Comment by neoaggelos** [comment] 2023-01-13 19:23
Hi @ctromans, thanks for reporting the issue. We have seen in the past and the root cause was a vxlan related issue which breaks packet checksums.

Can you check to see if the following resolves your issue:

```bash
sudo microk8s kubectl patch felixconfigurations default --patch '{"spec":{"featureDetectOverride":"ChecksumOffloadBroken=true"}}' --type=merge
```

**Comment by ctromans** [comment] 2023-01-16 21:51
Thanks @neoaggelos, that seems to have done the trick and it is working now.  Thank you so much for your help.

**Comment by neoaggelos** [comment] 2023-01-19 07:25
Good to hear, is it OK to close the issue then?

**Closed** 2023-01-19 10:30 UTC
