### ISSUE TITLE
CSINode is not yet initialized after enabling RBAC 

### ISSUE THREAD

**Issue by scottrus** [canonical/microk8s#3270] opened 2022-06-22 19:08 UTC
#### Summary
Enabled RBAC add-on and one of three nodes shows *CSINode is not yet initialized*

#### What Should Happen Instead?
Expected all nodes to be Ready after enabling RBAC addon

#### Reproduction Steps

1. Install Ubuntu Core 22 on 3x Intel NUC 11 systems2. 
2. Install microk8s with `snap install microk8s --channel=latest/edge/strict` 
3. Verify all nodes online with `kubectl get nodes -owide`
4. Enable RBAC with `microk8s enable rbac`

[inspection-report-20220622_185138.tar.gz](https://github.com/canonical/microk8s/files/8960620/inspection-report-20220622_185138.tar.gz)

#### Can you suggest a fix?
In my case, k8s-node-03 shows CSINode is not yet initialized preventing the node from coming ready. Possibly related to RBAC permissions not allowing the node to update a resource?

**Comment by ktsakalozos** [comment] 2022-06-27 07:25
Hi @scottrus

I am not able to reproduce this issue. The strict branch is under development so it is possible this issue is fixed as I remember there was something similar on the classic branch. Where do you see the `CSINode is not yet initialized`. Could you share the respective log file and a dmesg output?

**Comment by scottrus** [comment] 2022-06-27 11:30
Is there a more stable branch that can be used on Core 22? I’m not able to run `--classic`.

I removed MicroK8s snap and used `hostnamectl` to change the system name from `k8s-node-03.localdomain` to just `k8s-node-03`. After that I could not recreate the issue either. 

It’s not clear if something changed in the strict branch or the hostname change resolved it.

**Comment by ktsakalozos** [comment] 2022-06-28 06:52
> Is there a more stable branch that can be used on Core 22?

On Core you need a strictly confined snap and right now the latest/edge/strict branch provides the only such build of MicroK8s. With 1.25 we will have a dedicated track.

**Comment by PeterSR** [comment] 2022-11-27 08:26
We are facing the same issue on a node with `v1.21.13-3+cbc10c94808907`. It causes the node to be unready with the following conditions:

```
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Sun, 20 Nov 2022 00:52:25 +0100   Sun, 20 Nov 2022 00:52:25 +0100   CalicoIsUp                   Calico is running on this node
  MemoryPressure       False   Sun, 27 Nov 2022 09:21:50 +0100   Sun, 27 Nov 2022 09:21:50 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Sun, 27 Nov 2022 09:21:50 +0100   Sun, 27 Nov 2022 09:21:50 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Sun, 27 Nov 2022 09:21:50 +0100   Sun, 27 Nov 2022 09:21:50 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                False   Sun, 27 Nov 2022 09:21:50 +0100   Sun, 27 Nov 2022 09:21:50 +0100   KubeletNotReady              CSINode is not yet initialized
```

**Comment by PeterSR** [comment] 2022-11-27 08:48
We ended up using the following workaround:

Add 

```
--feature-gates=CSIMigration=false
```

to the end of `/var/snap/microk8s/current/args/kubelet` and then restart `kubelite` with 

```
sudo systemctl restart snap.microk8s.daemon-kubelite
```

We are still waiting on final confirm whether the node can start all pods again, but currently the node is in ready state:

```
Ready                True    Sun, 27 Nov 2022 09:47:24 +0100   Sun, 27 Nov 2022 09:47:24 +0100   KubeletReady                 kubelet is posting ready status. AppArmor enabled
```

**Comment by KagariSan** [comment] 2023-01-02 13:53
Confirm still having this problem on v1.26.0 revision 4390.
Have to disable RBAC to work around ATM.

**Comment by michael-mri** [comment] 2023-01-05 13:52
Had the same problem on my laptop, hostname had an uppercase and that created the following permission problems (from `snap logs -f microk8s`):

```
2023-01-05T14:26:35+01:00 microk8s.daemon-kubelite[10253]: W0105 14:26:35.588382   10253 reflector.go:424] object-"kube-system"/"kube-root-ca.crt": failed to list *v1.ConfigMap: configmaps "kube-root-ca.crt" is forbidden: User "system:node:Luhman16" cannot list resource "configmaps" in API group "" in the namespace "kube-system": no relationship found between node 'Luhman16' and this object
2023-01-05T14:26:35+01:00 microk8s.daemon-kubelite[10253]: E0105 14:26:35.588426   10253 reflector.go:140] object-"kube-system"/"kube-root-ca.crt": Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "kube-root-ca.crt" is forbidden: User "system:node:Luhman16" cannot list resource "configmaps" in API group "" in the namespace "kube-system": no relationship found between node 'Luhman16' and this object
2023-01-05T14:26:35+01:00 microk8s.daemon-kubelite[10253]: W0105 14:26:35.588611   10253 reflector.go:424] object-"kube-system"/"kubernetes-services-endpoint": failed to list *v1.ConfigMap: configmaps "kubernetes-services-endpoint" is forbidden: User "system:node:Luhman16" cannot list resource "configmaps" in API group "" in the namespace "kube-system": no relationship found between node 'Luhman16' and this object
2023-01-05T14:26:35+01:00 microk8s.daemon-kubelite[10253]: W0105 14:26:35.588639   10253 reflector.go:424] object-"kube-system"/"calico-config": failed to list *v1.ConfigMap: configmaps "calico-config" is forbidden: User "system:node:Luhman16" cannot list resource "configmaps" in API group "" in the namespace "kube-system": no relationship found between node 'Luhman16' and this object
2023-01-05T14:26:35+01:00 microk8s.daemon-kubelite[10253]: E0105 14:26:35.588660   10253 reflector.go:140] object-"kube-system"/"kubernetes-services-endpoint": Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "kubernetes-services-endpoint" is forbidden: User "system:node:Luhman16" cannot list resource "configmaps" in API group "" in the namespace "kube-system": no relationship found between node 'Luhman16' and this object
2023-01-05T14:26:35+01:00 microk8s.daemon-kubelite[10253]: E0105 14:26:35.588667   10253 reflector.go:140] object-"kube-system"/"calico-config": Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "calico-config" is forbidden: User "system:node:Luhman16" cannot list resource "configmaps" in API group "" in the namespace "kube-system": no relationship found between node 'Luhman16' and this object
```

Fixed the problem by:
- changing the hostname of my laptop to lower case
- `snap remove --purge microk8s`
- reboot
- `snap install microk8s`
- `microk8s enable rbac`

**Comment by KagariSan** [comment] 2023-01-07 14:42
@michael-mri 
Thank you. I confirm that change to lower case fixed the issue.
Now my cluster are up and running without any issue.

**Comment by reinvantveer** [comment] 2023-02-05 15:55
As much as I appreciate the effort @KagariSan I would like to politely disagree with the idea that this issue can be closed as completed @ktsakalozos. The shell script changes in #3681 offer a workaround, but the idea that something as vital as RBAC does not appear to work with hostnames with upper-case letters in them should be resolved, not warned, I believe. @ktsakalozos could you be so kind as to reopen the issue?

**Comment by neoaggelos** [comment] 2023-02-06 08:36
Hi @reinvantveer, thanks for the feedback. In general, uppercase hostnames can be troublesome in Kubernetes (as you may already know).

https://github.com/canonical/microk8s/pull/3731 should help with this

**Comment by reinvantveer** [comment] 2023-02-06 09:05
> Hi @reinvantveer, thanks for the feedback. In general, uppercase hostnames can be troublesome in Kubernetes (as you may already know).
@neoaggelos much obliged. I've done a few k8s deployments but have never run into this before, guess I've been lucky thus far...

> #3731 should help with this
Wow, that was impressively quick!

**Closed** 2023-02-09 15:53 UTC

**Comment by reinvantveer** [comment] 2023-02-09 16:34
:heart:

**Comment by meekara** [comment] 2023-02-19 22:25
I have same issue with a test environment composed of 3 lxc vm below are my system outputs.
How can I fix this problem ? I tried to **--feature-gates=CSIMigration=false to /var/snap/microk8s/current/args/kubelet**
but I got another error saying  below

_2023-02-19T22:25:01Z microk8s.daemon-kubelite[42410]: Error: failed to set feature gates from initial flags-based config: cannot set feature gate CSIMigration to false, feature is locked to true
2023-02-19T22:25:01Z microk8s.daemon-kubelite[42410]: F0219 22:25:01.261535   42410 daemon.go:57] Kubelet exited failed to set feature gates from initial flags-based config: cannot set feature gate CSIMigration to false, feature is locked to true_


```
root@microk8s02:~# kubectl get nodes
NAME         STATUS     ROLES    AGE    VERSION
microk8s01   Ready      <none>   2d8h   v1.26.1
microk8s03   NotReady   <none>   2d7h   v1.26.1
microk8s02   NotReady   <none>   2d7h   v1.26.1
```

```
2023-02-19T22:18:33Z microk8s.daemon-kubelite[38137]: I0219 22:18:33.261059   38137 setters.go:548] "Node became not ready" node="microk8s02" condition={Type:Ready Status:False LastHeartbeatTime:2023-02-19 22:18:33.261017752 +0000 UTC m=+65.164534534 LastTransitionTime:2023-02-19 22:18:33.261017752 +0000 UTC m=+65.164534534 Reason:KubeletNotReady Message:CSINode is not yet initialized}
2023-02-19T22:18:33Z microk8s.daemon-kubelite[38137]: I0219 22:18:33.364439   38137 setters.go:548] "Node became not ready" node="microk8s02" condition={Type:Ready Status:False LastHeartbeatTime:2023-02-19 22:18:33.364356664 +0000 UTC m=+65.267873576 LastTransitionTime:2023-02-19 22:18:33.364356664 +0000 UTC m=+65.267873576 Reason:KubeletNotReady Message:CSINode is not yet initialized}
```

```
root@microk8s02:~# microk8s status
microk8s is running
high-availability: yes
  datastore master nodes: 10.250.10.101:19001 10.250.10.103:19001 10.250.10.102:19001
  datastore standby nodes: none
addons:
  enabled:
    dashboard            # (core) The Kubernetes dashboard
    dns                  # (core) CoreDNS
    ha-cluster           # (core) Configure high availability on the current node
    helm                 # (core) Helm - the package manager for Kubernetes
    helm3                # (core) Helm 3 - the package manager for Kubernetes
    hostpath-storage     # (core) Storage class; allocates storage from host directory
    ingress              # (core) Ingress controller for external access
    metallb              # (core) Loadbalancer for your Kubernetes cluster
    metrics-server       # (core) K8s Metrics Server for API access to service metrics
    rbac                 # (core) Role-Based Access Control for authorisation
    registry             # (core) Private image registry exposed on localhost:32000
    storage              # (core) Alias to hostpath-storage add-on, deprecated
  disabled:
    cert-manager         # (core) Cloud native certificate management
    community            # (core) The community addons repository
    gpu                  # (core) Automatic enablement of Nvidia CUDA
    host-access          # (core) Allow Pods connecting to Host services smoothly
    kube-ovn             # (core) An advanced network fabric for Kubernetes
    mayastor             # (core) OpenEBS MayaStor
    minio                # (core) MinIO object storage
    observability        # (core) A lightweight observability stack for logs, traces and metrics
    prometheus           # (core) Prometheus operator for monitoring and logging
```

**Comment by dgitw** [comment] 2024-06-29 00:06
Issue also seems to occur with hyphens in host name :(
