### ISSUE TITLE
error: git cmd = '/snap/microk8s/4175/usr/bin/git fetch --depth=1 origin master': exit status 128

### ISSUE THREAD

**Issue by khteh** [canonical/microk8s#3587] opened 2022-11-24 06:04 UTC
```
$ k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.8-2+1dda18a15eea38", GitCommit:"1dda18a15eea38645814deffa547fe1c30141ef2", GitTreeState:"clean", BuildDate:"2022-11-10T18:01:19Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.8-2+1dda18a15eea38", GitCommit:"1dda18a15eea38645814deffa547fe1c30141ef2", GitTreeState:"clean", BuildDate:"2022-11-10T17:58:39Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
$ k apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
error: git cmd = '/snap/microk8s/4175/usr/bin/git fetch --depth=1 origin master': exit status 128
```
#### Reproduction Steps

1. ...
2. ...

**Comment by neoaggelos** [comment] 2022-11-24 07:48
I'm unable to reproduce this on either 1.25 or 1.24:

```
# 1.25
ubuntu@uk8s:~$ sudo microk8s kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
serviceaccount/ebs-csi-controller-sa created
serviceaccount/ebs-csi-node-sa created
clusterrole.rbac.authorization.k8s.io/ebs-csi-node-role created
clusterrole.rbac.authorization.k8s.io/ebs-external-attacher-role created
clusterrole.rbac.authorization.k8s.io/ebs-external-provisioner-role created
clusterrole.rbac.authorization.k8s.io/ebs-external-resizer-role created
clusterrole.rbac.authorization.k8s.io/ebs-external-snapshotter-role created
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-attacher-binding created
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-node-getter-binding created
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-provisioner-binding created
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-resizer-binding created
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-snapshotter-binding created
deployment.apps/ebs-csi-controller created
poddisruptionbudget.policy/ebs-csi-controller created
daemonset.apps/ebs-csi-node created
csidriver.storage.k8s.io/ebs.csi.aws.com created
```

And on 1.24:

```
ubuntu@uk8s:~$ microk8s kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.8-2+1dda18a15eea38", GitCommit:"1dda18a15eea38645814deffa547fe1c30141ef2", GitTreeState:"clean", BuildDate:"2022-11-10T18:01:19Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.8-2+1dda18a15eea38", GitCommit:"1dda18a15eea38645814deffa547fe1c30141ef2", GitTreeState:"clean", BuildDate:"2022-11-10T17:58:39Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
ubuntu@uk8s:~$ microk8s kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
serviceaccount/ebs-csi-controller-sa unchanged
serviceaccount/ebs-csi-node-sa unchanged
clusterrole.rbac.authorization.k8s.io/ebs-csi-node-role unchanged
clusterrole.rbac.authorization.k8s.io/ebs-external-attacher-role unchanged
clusterrole.rbac.authorization.k8s.io/ebs-external-provisioner-role unchanged
clusterrole.rbac.authorization.k8s.io/ebs-external-resizer-role unchanged
clusterrole.rbac.authorization.k8s.io/ebs-external-snapshotter-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-attacher-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-node-getter-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-provisioner-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-resizer-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/ebs-csi-snapshotter-binding unchanged
deployment.apps/ebs-csi-controller configured
poddisruptionbudget.policy/ebs-csi-controller configured
daemonset.apps/ebs-csi-node configured
csidriver.storage.k8s.io/ebs.csi.aws.com unchanged
```

Could this have been a temporary outage error? Can you try again and see if the issue persists?

**Comment by khteh** [comment] 2022-11-24 08:00
I decided to `apply -k` from my local cloned repo.

**Comment by neoaggelos** [comment] 2022-11-24 08:05
> I decided to apply -k from my local cloned repo.

That is a proper workaround. Are you still having troubles with the original command?

**Comment by khteh** [comment] 2022-11-24 08:06
No

**Comment by neoaggelos** [comment] 2022-11-24 08:23
Thanks, closing this. Please re-open the issue if it occurs again.

**Closed** 2022-11-24 08:23 UTC

**Comment by khteh** [comment] 2022-12-01 05:31
microk8s.kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.4.6" > private-ecr-driver.yml

/open
/reopen

**Comment by neoaggelos** [comment] 2022-12-05 16:55
@khteh Are you sure the `release-1.4.6` reference is correct?

```
$ git clone https://github.com/kubernetes-sigs/aws-efs-csi-driver -b release-1.4.6
Cloning into 'aws-efs-csi-driver'...
fatal: Remote branch release-1.4.6 not found in upstream origin
```

Perhaps `v1.4.6` or `release-1.4` is what you are after?

**Comment by zeph** [comment] 2024-01-05 17:56
i'm having a similar issue... 
```
# kubectl apply --server-side -k "https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2.3.0"
error: git cmd = '/snap/microk8s/6236/usr/bin/git fetch --depth=1 origin v2.3.0': exit status 128

# microk8s version
MicroK8s v1.26.11 revision 6236
```

**Comment by neoaggelos** [comment] 2024-01-11 18:05
@zeph see https://github.com/canonical/microk8s/issues/3988#issuecomment-1630330167
